var searchData=
[
  ['raw_5fimu_5ftype_0',['raw_imu_type',['../structILLIXR_1_1raw__imu__type.html',1,'ILLIXR']]],
  ['reader_1',['reader',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3acam_5ftype_5fzed_20_3e_2',['reader&lt; ILLIXR::data_format::cam_type_zed &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3aimu_5fintegrator_5finput_20_3e_3',['reader&lt; ILLIXR::data_format::imu_integrator_input &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3aimu_5fraw_5ftype_20_3e_4',['reader&lt; ILLIXR::data_format::imu_raw_type &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3anetwork_5flatency_5fresult_20_3e_5',['reader&lt; ILLIXR::data_format::network_latency_result &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3aopenxr_5fview_5fframe_20_3e_6',['reader&lt; ILLIXR::data_format::openxr_view_frame &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3apose_3a_3ahead_5fpose_5ftype_20_3e_7',['reader&lt; ILLIXR::data_format::pose::head_pose_type &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3aquest_5fcontroller_5finput_20_3e_8',['reader&lt; ILLIXR::data_format::quest_controller_input &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3arendered_5fframe_20_3e_9',['reader&lt; ILLIXR::data_format::rendered_frame &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3argb_5fdepth_5ftype_20_3e_10',['reader&lt; ILLIXR::data_format::rgb_depth_type &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3asemantic_5fxr_3a_3avoice_5fquery_20_3e_11',['reader&lt; ILLIXR::data_format::semantic_xr::voice_query &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3adata_5fformat_3a_3astereo_5fframe_20_3e_12',['reader&lt; ILLIXR::data_format::stereo_frame &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3aswitchboard_3a_3aevent_5fwrapper_3c_20eigen_3a_3avector3f_20_3e_20_3e_13',['reader&lt; ILLIXR::switchboard::event_wrapper&lt; Eigen::Vector3f &gt; &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20illixr_3a_3aswitchboard_3a_3aevent_5fwrapper_3c_20illixr_3a_3atime_5fpoint_20_3e_20_3e_14',['reader&lt; ILLIXR::switchboard::event_wrapper&lt; ILLIXR::time_point &gt; &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['reader_3c_20pose_5ftype_20_3e_15',['reader&lt; POSE_TYPE &gt;',['../classILLIXR_1_1switchboard_1_1reader.html',1,'ILLIXR::switchboard']]],
  ['realsense_16',['realsense',['../classILLIXR_1_1realsense.html',1,'ILLIXR']]],
  ['record_17',['record',['../classILLIXR_1_1record.html',1,'ILLIXR']]],
  ['record_5fcoalescer_18',['record_coalescer',['../classILLIXR_1_1record__coalescer.html',1,'ILLIXR']]],
  ['record_5fheader_19',['record_header',['../classILLIXR_1_1record__header.html',1,'ILLIXR']]],
  ['record_5fimu_5fcam_20',['record_imu_cam',['../classILLIXR_1_1record__imu__cam.html',1,'ILLIXR']]],
  ['record_5flogger_21',['record_logger',['../classILLIXR_1_1record__logger.html',1,'ILLIXR']]],
  ['record_5frgb_5fdepth_22',['record_rgb_depth',['../classILLIXR_1_1record__rgb__depth.html',1,'ILLIXR']]],
  ['rect_23',['rect',['../structILLIXR_1_1data__format_1_1shapes_1_1rect.html',1,'ILLIXR::data_format::shapes']]],
  ['relative_5fclock_24',['relative_clock',['../classILLIXR_1_1relative__clock.html',1,'ILLIXR']]],
  ['render_5fpass_25',['render_pass',['../classILLIXR_1_1vulkan_1_1render__pass.html',1,'ILLIXR::vulkan']]],
  ['rendered_5fframe_26',['rendered_frame',['../structILLIXR_1_1data__format_1_1rendered__frame.html',1,'ILLIXR::data_format']]],
  ['rendering_5fparams_27',['rendering_params',['../structILLIXR_1_1rendering__params.html',1,'ILLIXR']]],
  ['requested_5foption_5fnot_5fpresent_28',['requested_option_not_present',['../classcxxopts_1_1exceptions_1_1requested__option__not__present.html',1,'cxxopts::exceptions']]],
  ['rgb_5fdepth_5ftype_29',['rgb_depth_type',['../structILLIXR_1_1data__format_1_1rgb__depth__type.html',1,'ILLIXR::data_format']]],
  ['rk4_5fintegrator_30',['rk4_integrator',['../classILLIXR_1_1rk4__integrator.html',1,'ILLIXR']]],
  ['runtime_31',['runtime',['../classILLIXR_1_1runtime.html',1,'ILLIXR']]],
  ['runtime_5fimpl_32',['runtime_impl',['../classruntime__impl.html',1,'']]]
];
