LDFLAGS = -ldl -lX11 -pthread $(shell pkg-config glfw3 glew sqlite3 --libs)
# -lGLEW -lGL -lrt -lm -lGLU -lm -lGL -lm -ldl -lX11-xcb -lxcb-glx -ldrm -lXdamage -lXfixes -lxcb-dri2 -lXxf86vm -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp -lboost_thread
include common/common.mk
