LDFLAGS = -ggdb -lglfw -ldl -pthread -lGLEW -lGL -lX11
# -lrt -lm -lGLU -lm -lGL -lm -ldl -lX11-xcb -lxcb-glx -ldrm -lXdamage -lXfixes -lxcb-dri2 -lXxf86vm -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp -lboost_thread
include common/common.mk
