#!/usr/bin/env python3
# pylint: disable=line-too-long
# Copyright 2020-2026, The Board of Trustees of the University of Illinois.
# SPDX-License-Identifier: BSL-1.0
"""
generate_system_types.py

Scans include/illixr/data_format/*.hpp via libclang and writes one YAML file
per header into interfaces/system/illixr/data_format/.  These committed
YAML files describe ILLIXR system struct fields in the same schema used by
bridge type YAMLs, allowing the bridge generator to produce correct dict
conversion code for system types without requiring libclang at configure time.

Invocation
----------
  # From CMake (via SystemTypes.cmake):
  python3 generate_system_types.py --source-dir <ILLIXR_ROOT> --output-dir <interfaces/system>

  # Command line (with staleness check):
  python3 generate_system_types.py --source-dir /path/to/ILLIXR --output-dir ./system

  # Force regeneration even if nothing changed:
  python3 generate_system_types.py --source-dir /path/to/ILLIXR --output-dir ./system --force

Staleness
---------
A JSON state file (.system_types_state.json) in the output dir tracks MD5
hashes of all data_format headers.  The scan only runs when at least one
header has changed.

Output format
-------------
One YAML per header, e.g., system/illixr/data_format/combined_pose.yaml:

  # Auto-generated by generate_system_types.py - do not edit manually.
  # Source: include/illixr/data_format/combined_pose.hpp
  namespace: ILLIXR
  structs:
    combined_pose:
      fields:
        x: {type: float}
        y: {type: float}
        time_ns: {type: uint64}
        valid: {type: bool}
    fast_pose:
      base: illixr.data_format.combined_pose
      fields:
        vx: {type: float}

Dotted names follow the directory convention:
  ILLIXR::combined_pose   -> illixr.data_format.combined_pose
  ILLIXR::data_format::pose -> illixr.data_format.pose (sub-namespace preserved)

Eigen type mapping (C++ -> YAML):
  Eigen::Vector3f  -> type: float,  shape: [3]
  Eigen::Vector3d  -> type: double, shape: [3]
  Eigen::Vector4f  -> type: float,  shape: [4]
  Eigen::Quaternionf -> type: float, shape: [4]
  Eigen::Matrix3f  -> type: float,  shape: [3, 3]
  Eigen::Matrix4f  -> type: float,  shape: [4, 4]
  Eigen::Matrix4d  -> type: double, shape: [4, 4]

Unmappable types (custom templates, shared_ptr, etc.) are skipped with a
comment in the YAML.

Usage note: run this script whenever data_format/ headers change, then commit
the updated system/ YAML files.
"""
from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import re
import sys
from json import JSONDecodeError
from pathlib import Path
from typing import Tuple

try:
    import yaml
except ImportError:
    print("generate_system_types.py requires PyYAML: pip install pyyaml",
          file=sys.stderr)
    yaml = None
    sys.exit(1)

try:
    import clang.cindex as _clang
except ImportError:
    print("generate_system_types.py requires libclang: pip install clang",
          file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# YAML output helpers
# ---------------------------------------------------------------------------


# pylint: disable=too-many-ancestors
class _FlowListDumper(yaml.Dumper):
    """
    Custom YAML dumper that:
    - Renders lists in flow style: [3, 4] instead of block style (- 3\n- 4)
    - Disables aliases (no &id001 / *id001 for repeated objects)
    """
    def represent_sequence(self, tag, sequence, flow_style=None):
        # Always use flow style for sequences
        """Force flow style ``[a, b]`` for all YAML sequences.

        Args:
            tag (str): YAML tag.
            sequence: The sequence to represent.
            flow_style: Ignored; overridden to ``True``.

        Returns:
            yaml.SequenceNode: A flow-style sequence node.
        """
        return super().represent_sequence(tag, sequence, flow_style=True)

    def ignore_aliases(self, data):
        """Disable YAML aliases so repeated objects are always written in full.

        Args:
            data: Object being considered for aliasing.

        Returns:
            bool: Always ``True``.
        """
        return True


# ---------------------------------------------------------------------------
# C++ -> YAML type mapping
# ---------------------------------------------------------------------------

# Scalar C++ types -> YAML type name
_CPP_SCALAR_MAP = {
    "bool":           "bool",
    "char":           "int8",
    "signed char":    "int8",
    "unsigned char":  "uint8",
    "short":          "int16",
    "unsigned short": "uint16",
    "int":            "int",
    "unsigned int":   "uint32",
    "long":           "int64",
    "unsigned long":  "uint64",
    "long long":      "int64",
    "unsigned long long": "uint64",
    "float":          "float",
    "double":         "double",
    "std::string":    "string",
    "string":         "string",
    # stdint types
    "int8_t":   "int8",
    "int16_t":  "int16",
    "int32_t":  "int",
    "int64_t":  "int64",
    "uint8_t":  "uint8",
    "uint16_t": "uint16",
    "uint32_t": "uint32",
    "uint64_t": "uint64",
    }

# Known ILLIXR types defined outside data_format/ that have hand-maintained YAMLs.
# Maps C++ spelling variants -> dotted YAML type name.
_KNOWN_ILLIXR_REFS = {
    "time_point":              "illixr.time_point",
    "ILLIXR::time_point":      "illixr.time_point",
    }

# Eigen type spelling -> (yaml_type, shape_list, cpp_type)
# cpp_type is stored in the YAML so the writer can emit the correct Eigen construction.
_EIGEN_MAP = {
    "Eigen::Vector2f":    ("float",  [2],    "Eigen::Vector2f"),
    "Eigen::Vector2d":    ("double", [2],    "Eigen::Vector2d"),
    "Eigen::Vector3f":    ("float",  [3],    "Eigen::Vector3f"),
    "Eigen::Vector3d":    ("double", [3],    "Eigen::Vector3d"),
    "Eigen::Vector4f":    ("float",  [4],    "Eigen::Vector4f"),
    "Eigen::Vector4d":    ("double", [4],    "Eigen::Vector4d"),
    "Eigen::Quaternionf": ("float",  [4],    "Eigen::Quaternionf"),
    "Eigen::Quaterniond": ("double", [4],    "Eigen::Quaterniond"),
    "Eigen::Matrix2f":    ("float",  [2, 2], "Eigen::Matrix2f"),
    "Eigen::Matrix3f":    ("float",  [3, 3], "Eigen::Matrix3f"),
    "Eigen::Matrix3d":    ("double", [3, 3], "Eigen::Matrix3d"),
    "Eigen::Matrix4f":    ("float",  [4, 4], "Eigen::Matrix4f"),
    "Eigen::Matrix4d":    ("double", [4, 4], "Eigen::Matrix4d"),
    }


def _map_cpp_type(spelling: str, all_struct_names: set | None = None) -> dict | None:
    """
    Map a C++ type spelling to a YAML field descriptor dict.
    Returns None if the type cannot be mapped (will be skipped).
    """
    # pylint: disable=too-many-return-statements
    spelling = spelling.strip()

    # Strip const/volatile qualifiers
    spelling = re.sub(r'\b(const|volatile)\b\s*', '', spelling).strip()

    # Scalar
    if spelling in _CPP_SCALAR_MAP:
        return {"type": _CPP_SCALAR_MAP[spelling]}

    # Eigen - store cpp_type so the writer can construct the correct Eigen object
    if spelling in _EIGEN_MAP:
        yaml_type, shape, cpp_type = _EIGEN_MAP[spelling]
        return {"type": yaml_type, "shape": shape, "cpp_type": cpp_type}

    # std::array<T, N>
    m = re.match(r'^std::array<(.+),\s*(\d+)>$', spelling)
    if m:
        elem = _map_cpp_type(m.group(1))
        n = int(m.group(2))
        if elem and "shape" not in elem:
            return {"type": elem["type"], "shape": [n]}

    # std::vector<T>
    m = re.match(r'^std::vector<(.+)>$', spelling)
    if m:
        elem = _map_cpp_type(m.group(1).strip().rstrip(',').strip())
        if elem and "shape" not in elem and elem.get("type") not in (None, "string"):
            return {"type": elem["type"], "container": "vector"}

    # Check against known ILLIXR refs (types outside data_format/ with hand YAMLs)
    if spelling in _KNOWN_ILLIXR_REFS:
        return {"type": _KNOWN_ILLIXR_REFS[spelling]}

    # Check if the spelling refers to a known ILLIXR struct defined in data_format/.
    # Strip namespace prefixes: "data_format::pose::fast_head_pose_type" -> "fast_head_pose_type"
    if all_struct_names:
        bare = spelling.split("::")[-1].strip()
        if bare in all_struct_names:
            # Reconstruct a dotted name from the namespace prefix in the spelling
            # e.g. "data_format::pose::fast_head_pose_type"
            #   -> "illixr.data_format.pose.fast_head_pose_type"
            parts = [p.strip() for p in spelling.split("::")]
            # Drop leading "ILLIXR" if present, then prepend "illixr.data_format"
            if parts and parts[0] == "ILLIXR":
                parts = parts[1:]
            if parts and parts[0] == "data_format":
                parts = parts[1:]
            dotted = "illixr.data_format." + ".".join(p.lower() for p in parts)
            return {"type": dotted}

    return None  # unmappable


# ---------------------------------------------------------------------------
# libclang scanning
# ---------------------------------------------------------------------------

def _walk_namespace(cursor, ns_parts: list[str],
                    this_file: Path | None = None) -> list[tuple[list[str], object]]:
    """
    Walk cursor recursively, yielding (namespace_parts, struct_cursor) for
    every struct definition found inside any ILLIXR namespace path that is
    defined in this_file (not pulled in via #include).
    Handles nested namespaces (ILLIXR::data_format::pose etc.) correctly.
    """
    results = []
    for child in cursor.get_children():
        if child.kind == _clang.CursorKind.NAMESPACE:
            new_parts = ns_parts + [child.spelling] if ns_parts or child.spelling == "ILLIXR" else []
            if new_parts:
                results.extend(_walk_namespace(child, new_parts, this_file))
        elif (child.kind == _clang.CursorKind.STRUCT_DECL and
              child.spelling and child.is_definition() and
              ns_parts and ns_parts[0] == "ILLIXR"):
            # Only include structs defined in this header, not included ones
            if this_file is not None:
                loc = child.location.file
                if not (loc and Path(loc.name) == this_file):
                    continue
            results.append((ns_parts, child))
    return results


def _dotted_name(ns_parts: list[str], struct_name: str) -> str:
    """
    Convert namespace parts + struct name to dotted YAML name.
    All names are rooted at illixr.data_format since every header lives
    under include/illixr/data_format/.  The data_format namespace component
    is stripped to avoid doubling:

      ["ILLIXR"]                           -> illixr.data_format.combined_pose
      ["ILLIXR", "data_format"]            -> illixr.data_format.struct_name
      ["ILLIXR", "data_format", "pose"]    -> illixr.data_format.pose.struct_name
    """
    # Drop the "ILLIXR" prefix, then drop the leading "data_format" if present
    # (it is already encoded in the fixed illixr.data_format root)
    inner = ns_parts[1:]
    if inner and inner[0].lower() == "data_format":
        inner = inner[1:]
    sub = ".".join(p.lower() for p in inner)
    if sub:
        return f"illixr.data_format.{sub}.{struct_name}"
    return f"illixr.data_format.{struct_name}"


def scan_header(hdr: Path, include_root: Path,
                all_struct_names: set[str]) -> Tuple:
    """
    Parse a single data_format header and return a dict:
      {struct_name: {dotted, namespace, base, fields, skipped_fields}}
    """
    # pylint: disable=too-many-locals,too-many-branches
    index = _clang.Index.create()
    tu = index.parse(
        str(hdr),
        args=["-std=c++17", "-x", "c++",
              "-I", str(include_root), "-undef"],
        options=(_clang.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES |
                 _clang.TranslationUnit.PARSE_INCOMPLETE),
        )

    structs: dict = {}

    # Collect #include dependencies on other data_format headers
    # so the YAML can document what other type files are needed.
    deps: list[str] = []
    for inc in tu.get_includes():
        inc_path = Path(inc.include.name)
        try:
            rel = inc_path.relative_to(include_root)
            rel_str = str(rel).replace("\\", "/")
            # Only note direct includes of data_format headers (not system headers)
            if ("illixr/data_format" in rel_str
                    and rel_str != str(hdr.relative_to(include_root)).replace("\\", "/")
                    and inc.depth == 1):  # depth==1 means directly included
                deps.append(rel_str)
        except ValueError:
            pass  # not under include_root - system header, skip

    for ns_parts, struct_cursor in _walk_namespace(tu.cursor, [], this_file=hdr):
        struct_name = struct_cursor.spelling
        dotted = _dotted_name(ns_parts, struct_name)

        # Find base class (first CXX_BASE_SPECIFIER child)
        base_dotted = None
        for child in struct_cursor.get_children():
            if child.kind == _clang.CursorKind.CXX_BASE_SPECIFIER:
                base_spelling = child.type.spelling
                # Strip ILLIXR:: prefix and look up in known names
                base_name = base_spelling.split("::")[-1]
                if base_name in all_struct_names:
                    base_dotted = f"illixr.data_format.{base_name}"
                break

        # Extract direct (non-inherited) fields
        fields: dict = {}
        skipped: list[str] = []

        for child in struct_cursor.get_children():
            if child.kind != _clang.CursorKind.FIELD_DECL:
                continue
            field_name = child.spelling
            spelling = child.type.spelling
            mapped = _map_cpp_type(spelling, all_struct_names)
            if mapped:
                fields[field_name] = mapped
            else:
                skipped.append(f"{field_name}: {spelling}")

        # Track _KNOWN_ILLIXR_REFS types used in fields as additional deps
        ref_deps = set()
        for field_def in fields.values():
            field_type = field_def.get("type", "")
            if isinstance(field_type, str):
                for cpp_spelling, dotted_ref in _KNOWN_ILLIXR_REFS.items():
                    if field_type == dotted_ref:
                        ref_deps.add(cpp_spelling)

        structs[struct_name] = {
            "dotted": dotted,
            "namespace": ".".join(p.lower() for p in ns_parts),
            "base": base_dotted,
            "fields": fields,
            "skipped": skipped,
            "ref_deps": sorted(ref_deps),
            }

    return structs, deps


# ---------------------------------------------------------------------------
# YAML emission
# ---------------------------------------------------------------------------

def emit_header_yaml(structs: dict, rel_hdr: str, dependencies: list | None = None) -> str:
    """
    Produce the YAML text for one data_format header using yaml.dump()
    for correct escaping and structure.

    Comments (source header path, skipped fields) are prepended/appended
    as plain strings since PyYAML does not support inline comments.
    """
    # pylint: disable=too-many-locals
    def _deps_comment(dependencies_):
        """Format dependency paths as YAML comment lines.

        Args:
            dependencies_ (list[str]): Dependency paths or ``[system ref]`` strings.

        Returns:
            str: Comment block string, or ``""`` if dependencies_ is empty.
        """
        if not dependencies:
            return ""
        lines = ["# Depends on:"]
        for d in sorted(set(dependencies_)):
            lines.append(f"#   {d}")
        return "\n".join(lines) + "\n"

    if not structs:
        return (
            f"# Auto-generated by generate_system_types.py - do not edit manually.\n"
            f"# Source: {rel_hdr}\n"
            + _deps_comment(dependencies or [])
            + "# No mappable ILLIXR structs found in this header.\n"
            )

    # Build the data structure that yaml.dump will serialize.
    # Field descriptors: strip None values so the YAML stays compact.
    structs_data = {}
    for struct_name, info in sorted(structs.items()):
        entry: dict = {
            "dotted": info["dotted"],
            "namespace": info["namespace"],
            }
        if info["base"]:
            entry["base"] = info["base"]

        fields = {}
        for field_name, field_def in info["fields"].items():
            # Keep only non-None keys to avoid cluttering the YAML
            compact = {k: v for k, v in field_def.items() if v is not None}
            # shape lists must stay as lists (yaml.dump handles them correctly)
            fields[field_name] = compact if len(compact) > 1 else compact.get("type", compact)
        entry["fields"] = fields or {}

        structs_data[struct_name] = entry

    body = yaml.dump(
        {"structs": structs_data},
        Dumper=_FlowListDumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        )

    # Build skipped-fields comments (yaml.dump cannot emit comments)
    skipped_comments = []
    for struct_name, info in sorted(structs.items()):
        if info["skipped"]:
            skipped_comments.append(f"# {struct_name} — skipped fields (unmappable C++ types):")
            for s in info["skipped"]:
                skipped_comments.append(f"#   {s}")

    dep_comment = _deps_comment(dependencies or []).rstrip()
    parts = [
        "# Auto-generated by generate_system_types.py - do not edit manually.",
        f"# Source: {rel_hdr}",
        ]
    if dep_comment:
        parts.append(dep_comment)
    parts += [
        "",
        body.rstrip(),
        ]
    if skipped_comments:
        parts.append("")
        parts.extend(skipped_comments)
    parts.append("")  # trailing newline
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Staleness check
# ---------------------------------------------------------------------------

def _md5(path: Path) -> str:
    """Return the hex MD5 digest of a file.

    Args:
        path (Path): File to hash.

    Returns:
        str: Hex MD5 digest string.
    """
    return hashlib.md5(path.read_bytes()).hexdigest()


def _load_state(state_file: Path) -> dict:
    """Load staleness state from a JSON file.

    Args:
        state_file (Path): Path to the state JSON file.

    Returns:
        dict: Saved state, or ``{}`` if absent or unreadable.
    """
    if state_file.exists():
        with contextlib.suppress(JSONDecodeError, TypeError):
            return json.loads(state_file.read_text())
    return {}


def _save_state(state_file: Path, state: dict) -> None:
    """Persist staleness state to a JSON file.

    Args:
        state_file (Path): Destination path.
        state (dict): State dict to persist.

    Returns:
        None
    """
    state_file.write_text(json.dumps(state, indent=2))


def _headers_stale(data_format_dir: Path, state: dict) -> bool:
    """Return True if any header has changed since the last run."""
    current = {
        str(h): _md5(h)
        for h in sorted(data_format_dir.rglob("*.hpp"))
        if "serialization" not in h.parts
        }
    return current != state.get("header_hashes", {})


def _current_hashes(data_format_dir: Path) -> dict:
    """Return MD5 hashes of all data_format headers, excluding ``serialization/``.

    Args:
        data_format_dir (Path): ``include/illixr/data_format/`` directory.

    Returns:
        dict[str, str]: Map of absolute path string to hex MD5 digest.
    """
    return {
        str(h): _md5(h)
        for h in sorted(data_format_dir.rglob("*.hpp"))
        if "serialization" not in h.parts
        }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run(source_dir: Path, output_dir: Path, force: bool = False) -> None:
    """Scan data_format headers and write system type YAML files.

    Only runs when headers have changed (MD5 staleness check) unless ``force=True``.

    Args:
        source_dir (Path): ILLIXR repository root.
        output_dir (Path): Directory to write YAML files into.
        force (bool): Regenerate all YAMLs even if unchanged. Defaults to ``False``.

    Returns:
        None
    """
    # pylint: disable=too-many-locals
    data_format_dir = source_dir / "include" / "illixr" / "data_format"
    include_root = source_dir / "include"

    if not data_format_dir.exists():
        print(f"data_format directory not found: {data_format_dir}", file=sys.stderr)
        sys.exit(1)

    out_dir = output_dir / "illixr" / "data_format"
    state_file = output_dir / ".system_types_state.json"
    state = _load_state(state_file)

    if not force and not _headers_stale(data_format_dir, state):
        print("System types up to date - nothing to do.", file=sys.stderr)
        return

    print("Scanning data_format headers...", file=sys.stderr)
    out_dir.mkdir(parents=True, exist_ok=True)

    headers = sorted(
        h for h in data_format_dir.rglob("*.hpp")
        if "serialization" not in h.parts
        )

    # First pass: collect all struct names across all headers so base class
    # lookups work even when the base is defined in a different header.
    all_struct_names: set[str] = set()
    index = _clang.Index.create()
    for hdr in headers:
        tu = index.parse(
            str(hdr),
            args=["-std=c++17", "-x", "c++",
                  "-I", str(include_root), "-undef"],
            options=(_clang.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES |
                     _clang.TranslationUnit.PARSE_INCOMPLETE),
            )
        for _, sc in _walk_namespace(tu.cursor, [], this_file=hdr):
            all_struct_names.add(sc.spelling)

    # Second pass: full extraction and YAML emission
    for hdr in headers:
        rel = str(hdr.relative_to(source_dir / "include")).replace("\\", "/")
        structs, dependencies = scan_header(hdr, include_root, all_struct_names)
        # Add ref_deps from each struct (KNOWN_ILLIXR_REFS types used as field types)
        for sinfo in structs.values():
            for ref in sinfo.get("ref_deps", []):
                ref_dotted = _KNOWN_ILLIXR_REFS.get(ref, "")
                if ref_dotted and ref_dotted not in dependencies:
                    dependencies.append(f"[system ref] {ref_dotted}")

        yaml_text = emit_header_yaml(structs, rel, dependencies=dependencies)
        # Mirror source subdirectory structure under out_dir
        # e.g. data_format/poses/fast_pose.hpp -> system/illixr/data_format/poses/fast_pose.yaml
        rel_subdir = hdr.relative_to(data_format_dir).parent
        out_subdir = out_dir / rel_subdir
        out_subdir.mkdir(parents=True, exist_ok=True)
        out_file = out_subdir / hdr.with_suffix(".yaml").name
        out_file.write_text(yaml_text)
        n = len(structs)
        rel_out = out_file.relative_to(output_dir)
        print(f"  {hdr.relative_to(data_format_dir.parent)} -> {rel_out}  ({n} struct{'s' if n != 1 else ''})",
              file=sys.stderr)

    # Update state
    _save_state(state_file, {"header_hashes": _current_hashes(data_format_dir)})
    print(f"System type YAMLs written to {out_dir}", file=sys.stderr)


def main() -> None:
    """Parse command-line arguments and invoke ``run()``.

    Returns:
        None
    """
    parser = argparse.ArgumentParser(
        description="Scan ILLIXR data_format headers and write system type YAMLs.")
    parser.add_argument(
        "--source-dir", required=True, type=Path,
        help="ILLIXR repository root (contains include/illixr/data_format/)")
    parser.add_argument(
        "--output-dir", required=True, type=Path,
        help="Directory to write system/ YAML files into (e.g., interfaces/system)")
    parser.add_argument(
        "--force", action="store_true",
        help="Regenerate even if headers have not changed")
    args = parser.parse_args()

    run(args.source_dir, args.output_dir, force=args.force)


if __name__ == "__main__":
    main()
