// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.point_cloud

#pragma once

#include "illixr/switchboard.hpp"

#include <boost/serialization/vector.hpp>
#include <vector>

namespace ILLIXR::data_format::semantic_xr {
struct point_cloud : switchboard::event {
    std::vector<float> points;
    std::vector<float> centroid;
    int32_t            num_points;

    point_cloud() = default;
};

} // namespace ILLIXR::data_format::semantic_xr
