// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.query_response

#pragma once

#include "illixr/switchboard.hpp"

#include "point_cloud.hpp"

#include <boost/serialization/string.hpp>
#include <boost/serialization/vector.hpp>
#include <vector>

namespace ILLIXR {
namespace bridge {
namespace semantic_xr {

struct query_response : switchboard::event {
    uint64_t query_id_;
    std::vector<ILLIXR::bridge::semantic_xr::point_cloud> point_clouds_;
    std::vector<float> colors_;
    int32_t num_point_clouds_;
    float server_query_processing_;
    std::string text_query_;

    query_response() = default;
};

} // namespace semantic_xr
} // namespace bridge
} // namespace ILLIXR
