// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.query_response

#pragma once

#include "illixr/switchboard.hpp"

#include "point_cloud.hpp"

#include <boost/serialization/string.hpp>
#include <boost/serialization/vector.hpp>
#include <vector>

namespace ILLIXR::data_format::semantic_xr {

struct query_response : switchboard::event {
    uint64_t query_id;
    std::vector<ILLIXR::data_format::semantic_xr::point_cloud> point_clouds;
    std::vector<float> colors;
    int32_t num_point_clouds;
    float server_query_processing;
    std::string text_query;

    query_response() = default;
};

} // namespace ILLIXR::data_format::semantic_xr
