// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.query_response

#pragma once

#include "query_response.hpp"
#include "point_cloud_ser.hpp"

#include <boost/serialization/array.hpp>
#include <boost/serialization/export.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/base_object.hpp>
namespace boost {
namespace serialization {

template<class Archive>
void serialize(Archive& ar, ILLIXR::bridge::semantic_xr::query_response& data, const unsigned int) {
    ar & boost::serialization::base_object<ILLIXR::switchboard::event>(data);
    ar & data.query_id_;
    ar & data.point_clouds_;
    ar & data.colors_;
    ar & data.num_point_clouds_;
    ar & data.server_query_processing_;
    ar & data.text_query_;
}

} // namespace serialization
} // namespace boost

BOOST_CLASS_EXPORT_KEY(ILLIXR::bridge::semantic_xr::query_response)
