// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.voice_query

#pragma once

#include "illixr/switchboard.hpp"

#include <boost/serialization/vector.hpp>
#include <vector>

namespace ILLIXR {
namespace bridge {
namespace semantic_xr {

struct voice_query : switchboard::event {
    uint64_t query_id_;
    std::vector<uint8_t> pcm_data_;
    float similarity_threshold_;
    float min_match_similarity_;

    voice_query() = default;
};

} // namespace semantic_xr
} // namespace bridge
} // namespace ILLIXR
