# pylint: disable=line-too-long
# Copyright 2020-2026, The Board of Trustees of the University of Illinois.
# SPDX-License-Identifier: BSL-1.0
"""Plugin CMakeLists, hpp, and cpp code generation."""
from pathlib import Path

from . import types as bg_types
from . import helpers as bg_helpers
from . import codegen_struct as bg_cg_struct
from . import codegen_python_reader as bg_cg_reader
from . import codegen_python_writer as bg_cg_writer


def gen_plugin_cmake(bridge, gen_dotted_names, gen_serializers, plugin_dir,
                     build_include_dir):
    """Generate the ``CMakeLists.txt`` for a bridge plugin.

    Produces a CMake file that compiles the plugin into a shared library,
    links against ILLIXR runtime, pybind11, and any required third-party
    libraries (OpenCV, Boost.Serialization, etc.).

    Args:
        bridge (dict): Normalized bridge definition from ``validate_bridge_yaml``.
        gen_dotted_names (list[str]): All bridge-defined dotted type names.
        gen_serializers (list[str]): Dotted names of types that require Boost
                                      serialization (network outputs).
        plugin_dir (Path): Directory where the plugin sources will be written.
        build_include_dir (Path): CMake build directory (used for include paths).

    Returns:
        str: Complete ``CMakeLists.txt`` content.
    """

    plugin_name = bridge["name"]
    gen_headers = []
    for dotted in sorted(gen_dotted_names):
        hdr = (build_include_dir / "illixr" / "bridge" /
               (str(bg_helpers.dotted_to_path(dotted)) + ".hpp"))
        gen_headers.append(str(hdr))

    cmake = ["# Copyright 2020-" + bg_types.YEAR + ", The Board of Trustees of the University of Illinois.",
             "# SPDX-License-Identifier: BSL-1.0",
             "# This file was generated by generate_python_bridges.py -- do not edit directly.",
             "",
             "set(PLUGIN_NAME plugin." + plugin_name + "${ILLIXR_BUILD_SUFFIX})",
             "",
             "",
             "# Glob binding sources generated at configure time",
             'file(GLOB _BRIDGE_BINDINGS "' + str(plugin_dir) + '/bindings_*.cpp")',
             "",
             "add_library(${PLUGIN_NAME} SHARED",
             '    "' + str(plugin_dir) + '/plugin.cpp"',
             '    "' + str(plugin_dir) + '/plugin.hpp"',
             "    ${_BRIDGE_BINDINGS}"]
    # Do NOT call find_package(pybind11) here. pybind11 is already found
    # in the parent cmake scope, and its targets (pybind11::embed etc.) are
    # globally visible to subdirectories.  Re-calling find_package would
    # trigger FindPythonLibsNew again, conflicting with cached Python3
    # variables and causing PYTHON_LIBRARY-NOTFOUND on re-runs.
    for hdr in gen_headers:
        cmake.append('    "' + hdr + '"')
    for hdr in gen_serializers:
        cmake.append('    "' + hdr + '"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include/illixr/plugin.hpp"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include/illixr/switchboard.hpp"')
    cmake.append(")")
    cmake.append("")
    cmake.append("target_include_directories(${PLUGIN_NAME} PRIVATE")
    cmake.append('    "' + str(plugin_dir) + '"')
    cmake.append('    "' + str(build_include_dir) + '"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include"')
    cmake.append(")")
    cmake.append("")
    cmake.append("target_compile_definitions(${PLUGIN_NAME} PRIVATE")
    cmake.append("    PLUGIN_NAME=" + plugin_name)
    # Serialization is always compiled in - no per-type defines needed.
    cmake.append(")")
    cmake.append("")
    cmake.append("set_target_properties(${PLUGIN_NAME} PROPERTIES")
    cmake.append("    CXX_STANDARD 17")
    cmake.append("    CXX_STANDARD_REQUIRED ON")
    cmake.append(")")
    cmake.append("")
    cmake.append("target_link_libraries(${PLUGIN_NAME} PUBLIC")
    cmake.append("    pybind11::embed")
    cmake.append("    spdlog::spdlog")
    cmake.append("    Boost::serialization")
    cmake.append(")")
    cmake.append("")
    cmake.append("# Link OpenCV if available (needed for mat_* bridge fields)")
    cmake.append("if(TARGET opencv_core)")
    cmake.append("    target_link_libraries(${PLUGIN_NAME} PUBLIC opencv_core)")
    cmake.append("elseif(OpenCV_FOUND)")
    cmake.append("    target_link_libraries(${PLUGIN_NAME} PUBLIC ${OpenCV_LIBS})")
    cmake.append("endif()")
    cmake.append("")
    cmake.append("install(TARGETS ${PLUGIN_NAME} DESTINATION lib)")
    cmake.append("")
    return "\n".join(cmake)


# ---------------------------------------------------------------------------
# Plugin source generation
# ---------------------------------------------------------------------------

def gen_plugin_hpp(bridge, gen_dotted_names):
    """Generate the plugin class header (``plugin.hpp``) for a bridge.

    Declares the plugin class with switchboard reader and writer members,
    the Python thread method, and static network config helpers.

    Args:
        bridge (dict): Normalized bridge definition.
        gen_dotted_names (list[str]): All bridge-defined dotted type names.

    Returns:
        str: Complete ``plugin.hpp`` content.
    """
    # pylint: disable=too-many-statements
    plugin_name = bridge["name"]
    all_types = (
        {inp["type"] for inp in bridge["inputs"]} |
        {out["type"] for out in bridge["outputs"]}
        )
    type_includes = sorted(bg_cg_struct.include_for_type(t, gen_dotted_names) for t in all_types)

    hpp = [f"// Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
           "// SPDX-License-Identifier: BSL-1.0",
           "// This file was generated by generate_python_bridges.py -- do not edit directly.",
           "",
           "#pragma once",
           "",
           '#include "illixr/plugin.hpp"', '#include "illixr/switchboard.hpp"']
    for inc in type_includes:
        hpp.append(f"#include {inc}")
    hpp.append("")
    hpp.append("#include <pybind11/embed.h>")
    hpp.append("#include <string>")
    hpp.append("#include <thread>")
    hpp.append("#include <unordered_map>")
    hpp.append("")
    hpp.append("namespace py = pybind11;")
    hpp.append("")
    hpp.append("namespace ILLIXR {")
    hpp.append("")
    hpp.append(f"class {plugin_name} : public plugin {{")
    hpp.append("public:")
    hpp.append(f"    [[maybe_unused]] explicit {plugin_name}(const std::string& name, phonebook* pb);")
    hpp.append(f"    ~{plugin_name}() override;")
    hpp.append("")
    hpp.append("    void start() override;")
    hpp.append("")
    hpp.append("private:")
    hpp.append("    void run_python_thread();")
    hpp.append("    void parse_py_args(const std::string& input);")
    hpp.append("")
    hpp.append("    const std::shared_ptr<switchboard> switchboard_;")
    for inp in bridge["inputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(inp["type"], gen_dotted_names)
        hpp.append(f"    switchboard::reader<{cpp_t}> {inp['alias']}_reader_;")
    for out in bridge["outputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out["type"], gen_dotted_names)
        hpp.append(
            f"    switchboard::{'network_writer' if out['network'] != 'none' else 'writer'}<{cpp_t}> {out['alias']}_writer_;")
    hpp.append("")
    hpp.append("    pybind11::scoped_interpreter guard_;")
    hpp.append("    pybind11::gil_scoped_release  release_;")
    hpp.append("    std::thread                   py_thread_;")
    hpp.append("")
    # Static topic_config builders - one per transport type used.
    # Sequential field assignment avoids designated initializer syntax
    # which is not supported on MSVC.
    _net_types = set(out["network"] for out in bridge["outputs"]
                     if out["network"] != "none")
    if "tcp" in _net_types or "any" in _net_types:
        hpp.append("    static network::topic_config _make_tcp_config() {")
        hpp.append("        network::topic_config cfg;")
        hpp.append("        cfg.serialization_method = network::topic_config::BOOST;")
        hpp.append("        cfg.transport_method = network::topic_config::TCP;")
        hpp.append("        return cfg;")
        hpp.append("    }")
    if "udp" in _net_types:
        hpp.append("    static network::topic_config _make_udp_config() {")
        hpp.append("        network::topic_config cfg;")
        hpp.append("        cfg.serialization_method = network::topic_config::BOOST;")
        hpp.append("        cfg.transport_method = network::topic_config::UDP;")
        hpp.append("        return cfg;")
        hpp.append("    }")
    hpp.append("    std::unordered_map<std::string, std::string> py_args_;")
    hpp.append("    std::string                   py_exe_;")
    hpp.append("};")
    hpp.append("")
    hpp.append("} // namespace ILLIXR")
    hpp.append("")
    return "\n".join(hpp)


def gen_plugin_cpp(bridge, gen_dotted_names, script_yaml_default,
                   plugin_dir: Path, type_defs_map=None):
    """Generate the plugin implementation (``plugin.cpp``) for a bridge.

    This is the main generated file.  It embeds a Python interpreter and
    injects reader/writer handles into the script namespace.  For each
    input topic it generates a ``Py_<alias>_reader`` struct with a ``.get()``
    method; for each output topic a ``Py_<alias>_writer`` struct with a
    ``.put(dict)`` method; and an ``illixr_subscribe(alias, callback)``
    function for the event-driven subscription model.

    Args:
        bridge (dict): Normalized bridge definition.
        gen_dotted_names (list[str]): All bridge-defined dotted type names.
        script_yaml_default (str): Default script path compiled into the plugin
                                    (overridable at runtime via environment variable).
        plugin_dir (Path): Plugin directory
        type_defs_map (dict): Map of dotted name -> type definition dict, including
                               both bridge-defined and ILLIXR system types.

    Returns:
        str: Complete ``plugin.cpp`` content.
    """
    # pylint: disable=too-many-locals,too-many-branches,too-many-statements
    plugin_name = bridge["name"]
    plugin_name_upper = plugin_name.upper()
    # Environment variable names follow ILLIXR convention: ILLIXR_<NAME>_<KEY>
    env_script = f"ILLIXR_{plugin_name_upper}_SCRIPT"
    env_args = f"ILLIXR_{plugin_name_upper}_ARGS"

    cpp = [f"// Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
           "// SPDX-License-Identifier: BSL-1.0",
           "// This file was generated by generate_python_bridges.py -- do not edit directly.",
           "",
           '#include "plugin.hpp"',
           "",
           "#include <pybind11/embed.h>",
           "#include <pybind11/numpy.h>",
           "#include <pybind11/stl.h>",
           "#include <spdlog/spdlog.h>",
           "", "#include <filesystem>",
           "#include <stdexcept>",
           "#include <string>",
           "#include <thread>",
           "",
           "namespace py = pybind11;",
           "",
           "using namespace ILLIXR;",
           "",
           f"[[maybe_unused]] {plugin_name}::{plugin_name}(const std::string& name, phonebook* pb)",
           "    : plugin{name, pb}",
           "    , switchboard_{pb->lookup_impl<switchboard>()}"]

    # -----------------------------------------------------------------------
    # Constructor
    # -----------------------------------------------------------------------
    for inp in bridge["inputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(inp["type"], gen_dotted_names)
        cpp.append(f'    , {inp["alias"]}_reader_{{switchboard_->get_reader<{cpp_t}>("{inp["topic"]}")}}')
    for out in bridge["outputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out["type"], gen_dotted_names)
        net = out["network"]
        alias = out["alias"]
        topic = out["topic"]
        if net == "none":
            cpp.append(
                f'    , {alias}_writer_{{switchboard_->'
                f'get_writer<{cpp_t}>("{topic}")}}'
                )
        else:
            cfg_fn = "_make_udp_config" if net == "udp" else "_make_tcp_config"
            cpp.append(
                f'    , {alias}_writer_{{switchboard_->'
                f'get_network_writer<{cpp_t}>("{topic}", {cfg_fn}())}}'
                )
    cpp.append("    , guard_{}")
    cpp.append("    , release_{} {")
    cpp.append("")
    cpp.append("    // Set up venv site-packages if VIRTUAL_ENV is set.")
    cpp.append("    const char* venv = std::getenv(\"VIRTUAL_ENV\");")
    cpp.append("    if (venv) {")
    cpp.append("        py::gil_scoped_acquire acquire;")
    cpp.append("        py::module_ sys  = py::module_::import(\"sys\");")
    cpp.append("        py::module_ site = py::module_::import(\"site\");")
    cpp.append("        auto vi    = sys.attr(\"version_info\");")
    cpp.append("        int major  = vi.attr(\"major\").cast<int>();")
    cpp.append("        int minor  = vi.attr(\"minor\").cast<int>();")
    cpp.append("        std::string sp = std::string(venv) + \"/lib/python\" +")
    cpp.append("                         std::to_string(major) + \".\" +")
    cpp.append("                         std::to_string(minor) + \"/site-packages\";")
    cpp.append("        py::list path = sys.attr(\"path\");")
    cpp.append("        path.attr(\"insert\")(0, sp);")
    cpp.append("        site.attr(\"addsitedir\")(sp);")
    cpp.append("    }")
    cpp.append("")
    cpp.append(f'    // Script path: env var {env_script} overrides YAML default.')
    cpp.append(f'    const char* env_script = std::getenv("{env_script}");')
    cpp.append('    py_exe_ = env_script ? std::string(env_script)')
    cpp.append(f'                         : std::string("{script_yaml_default}");')
    cpp.append('    if (py_exe_.empty())')
    cpp.append(
        f'        throw std::runtime_error("[{plugin_name}] No script path: set {env_script} or provide script: in the bridge yaml.");')
    cpp.append("")
    cpp.append(f'    std::string arg_string = switchboard_->get_env("{env_args}", "");')
    cpp.append("    parse_py_args(arg_string);")
    cpp.append(f'    spdlog::get("illixr")->debug("[{plugin_name}] script: {{}}  args: {{}}", py_exe_, arg_string);')
    cpp.append("}")
    cpp.append("")

    # -----------------------------------------------------------------------
    # Destructor
    # -----------------------------------------------------------------------
    cpp.append(f"{plugin_name}::~{plugin_name}() {{")
    cpp.append("    if (py_thread_.joinable())")
    cpp.append("        py_thread_.join();")
    cpp.append("}")
    cpp.append("")

    # -----------------------------------------------------------------------
    # start()
    # -----------------------------------------------------------------------
    cpp.append(f"void {plugin_name}::start() {{")
    cpp.append(f"    py_thread_ = std::thread(&{plugin_name}::run_python_thread, this);")
    cpp.append("}")
    cpp.append("")

    # -----------------------------------------------------------------------
    # parse_py_args()  - identical to semantic_xr implementation
    # -----------------------------------------------------------------------
    cpp.append(f"void {plugin_name}::parse_py_args(const std::string& input) {{")
    cpp.append("    std::string::size_type start = 0;")
    cpp.append("    while (start < input.size()) {")
    cpp.append("        auto comma = input.find(',', start);")
    cpp.append("        if (comma == std::string::npos) comma = input.size();")
    cpp.append("        std::string token = input.substr(start, comma - start);")
    cpp.append("        if (!token.empty()) {")
    cpp.append("            auto eq = token.find('=');")
    cpp.append("            if (eq == std::string::npos) {")
    cpp.append('                py_args_[token] = "";')
    cpp.append("            } else if (eq == 0) {")
    cpp.append(f'                spdlog::get("illixr")->warn("[{plugin_name}] Malformed arg token \'{{}}\'", token);')
    cpp.append("            } else {")
    cpp.append("                py_args_[token.substr(0, eq)] = token.substr(eq + 1);")
    cpp.append("            }")
    cpp.append("        }")
    cpp.append("        start = comma + 1;")
    cpp.append("    }")
    cpp.append("}")
    cpp.append("")

    # -----------------------------------------------------------------------
    # run_python_thread()
    # -----------------------------------------------------------------------
    cpp.append(f"void {plugin_name}::run_python_thread() {{")
    cpp.append("    py::gil_scoped_acquire acquire;")
    cpp.append("    try {")
    cpp.append("        // Build sys.argv from parsed args")
    cpp.append("        py::list argv;")
    cpp.append("        argv.append(py_exe_);")
    cpp.append("        for (const auto& [key, val] : py_args_) {")
    cpp.append('            argv.append((key.size() == 1 ? "-" : "--") + key);')
    cpp.append('            if (!val.empty()) argv.append(val);')
    cpp.append("        }")
    cpp.append('        py::module_::import("sys").attr("argv") = argv;')
    cpp.append("")
    cpp.append('        // Add the plugin package dir so illixr.bridge.* resolves.')
    cpp.append('        py::module_ sys_mod = py::module_::import("sys");')
    cpp.append(f'        sys_mod.attr("path").attr("insert")(0, std::string("{plugin_dir}"));')
    cpp.append("")
    cpp.append("        // Inject reader/writer handles into globals.")
    cpp.append("        // Scripts access these as bare globals, no import needed.")
    cpp.append("        py::dict globals = py::globals();")
    cpp.append("")

    # Inject readers - each reader.get() returns a py::dict
    for inp in bridge['inputs']:
        alias = inp['alias']
        input_type = inp['type']
        global_name = f'illixr_{alias}_reader'
        td_for_type = (type_defs_map or {}).get(input_type)

        cpp.append(f'        // {global_name}.get() -> py::dict or None')
        cpp.append(f'        struct Py_{alias}_reader {{')
        cpp.append(f'            {plugin_name}* self_;')
        cpp.append('            py::object get() const {')
        cpp.append(f'                auto val = self_->{alias}_reader_.get_ro_nullable();')
        cpp.append('                if (!val) return py::none();')
        cpp.append('                py::dict _d;')
        if td_for_type:
            # val is a switchboard::ptr<const T> (shared_ptr-like),
            # so fields are accessed via val->field_ not val.field_
            for dict_line in bg_cg_reader.gen_reader_dict_body(
                td_for_type, gen_dotted_names, var="(*val)",
                type_defs_map=type_defs_map):
                cpp.append(dict_line)
        else:
            # ILLIXR system type - fall back to exposing raw cast
            cpp.append('                _d["value"] = py::cast(*val);')
        cpp.append('                return _d;')
        cpp.append('            }')
        cpp.append('        };')
        cpp.append('        {')
        cpp.append('        auto _mreg = py::module_::import("__main__");')
        cpp.append(f'        py::class_<Py_{alias}_reader>(_mreg,')
        cpp.append(f'            "_{plugin_name}_{alias}_reader_t")')
        cpp.append(f'            .def("get", &Py_{alias}_reader::get);')
        cpp.append('        }')
        cpp.append(f'        globals["{global_name}"] = Py_{alias}_reader{{this}};')
        cpp.append('')

    # Inject writers
    for out in bridge['outputs']:
        alias = out['alias']
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out['type'], gen_dotted_names)
        global_name = f'illixr_{alias}_writer'
        td_out = (type_defs_map or {}).get(out['type'])

        cpp.append(f"        // {global_name}.put(dict) -> publish to '{out['topic']}'")
        cpp.append(f'        struct Py_{alias}_writer {{')
        cpp.append(f'            {plugin_name}* self_;')
        cpp.append('            void put(py::object val) const {')
        cpp.append('                if (!py::isinstance<py::dict>(val)) {')
        cpp.append(f'                    throw py::type_error("illixr_{alias}_writer.put(): expected a dict");')
        cpp.append('                }')
        cpp.append(f'                {cpp_t} data;')
        cpp.append('                auto d = val.cast<py::dict>();')
        if td_out:
            for writer_line in bg_cg_writer.gen_writer_from_dict_body(td_out, gen_dotted_names,
                                                                      type_defs_map=type_defs_map):
                cpp.append(writer_line)
        cpp.append(f'                auto ev = self_->{alias}_writer_.allocate(std::move(data));')
        cpp.append(f'                self_->{alias}_writer_.put(std::move(ev));')
        cpp.append('            }')
        cpp.append('        };')
        cpp.append('        {')
        cpp.append('        auto _mreg = py::module_::import("__main__");')
        cpp.append(f'        py::class_<Py_{alias}_writer>(_mreg,')
        cpp.append(f'            "_{plugin_name}_{alias}_writer_t")')
        cpp.append(f'            .def("put", &Py_{alias}_writer::put);')
        cpp.append('        }')
        cpp.append(f'        globals["{global_name}"] = Py_{alias}_writer{{this}};')
        cpp.append('')

    # Inject 'subscribe' callable - callback receives a py::dict
    cpp.append('        globals["illixr_subscribe"] = py::cpp_function(')
    cpp.append('            [this](const std::string& alias, py::object callback) {')
    for inp in bridge['inputs']:
        inp_alias = inp['alias']
        inp_topic = inp['topic']
        inp_t = bg_cg_struct.cpp_type_for_switchboard(inp['type'], gen_dotted_names)
        td_inp = (type_defs_map or {}).get(inp['type'])
        cpp.append(f'                if (alias == "{inp_alias}") {{')
        cpp.append(f'                    switchboard_->schedule<{inp_t}>(')
        cpp.append(f'                        id_, "{inp_topic}",')
        cpp.append(f'                        [cb = callback](switchboard::ptr<const {inp_t}> val, std::size_t) {{')
        cpp.append('                            py::gil_scoped_acquire gil;')
        cpp.append('                            py::dict _d;')
        if td_inp:
            for dline in bg_cg_reader.gen_reader_dict_body(td_inp, gen_dotted_names,
                                                           var='(*val)', indent='                            ',
                                                           dict_var='_d', type_defs_map=type_defs_map):
                cpp.append(dline)
        cpp.append('                            cb(_d);')
        cpp.append('                        });')
        cpp.append('                    return;')
        cpp.append('                }')
    cpp.append('                throw py::value_error(')
    cpp.append('                    "illixr_subscribe: unknown alias \'" + alias + "\'.");')
    cpp.append('            });')
    cpp.append('')

    # Run the script
    cpp.append(f'        spdlog::get("illixr")->info("[{plugin_name}] Running script: {{}}", py_exe_);')
    cpp.append("        py::eval_file(py_exe_, globals);")
    cpp.append("")
    cpp.append("    } catch (const py::error_already_set& e) {")
    cpp.append(f'        spdlog::get("illixr")->error("[{plugin_name}] Python exception: {{}}", e.what());')
    cpp.append("    } catch (const std::exception& e) {")
    cpp.append(f'        spdlog::get("illixr")->error("[{plugin_name}] Exception: {{}}", e.what());')
    cpp.append("    }")
    cpp.append("}")
    cpp.append("")
    cpp.append(f"PLUGIN_MAIN({plugin_name})")
    cpp.append("")
    return "\n".join(cpp)

# ---------------------------------------------------------------------------
# Tier 1 - profile YAML generation
# ---------------------------------------------------------------------------
