# pylint: disable=line-too-long
# Copyright 2020-2026, The Board of Trustees of the University of Illinois.
# SPDX-License-Identifier: BSL-1.0
"""Unity bridge plugin.hpp / plugin.cpp / CMakeLists.txt generation.

Mirrors codegen_plugin.py's role but targets the P/Invoke boundary instead
of an embedded Python interpreter: no pybind11, no script -- just
switchboard::reader/writer members plus generated get_<alias>_* methods
and extern "C" exports, following the hand-written unity_component pattern.

Each bridge compiles into its own SHARED plugin library (like Python
bridges), discovered via the standard ILLIXR load_so + PLUGIN_MAIN
mechanism. A static instance pointer, set in the constructor, is what the
extern "C" P/Invoke exports resolve against -- there is exactly one
instance per plugin .so, so this is safe without needing to know how
PLUGIN_MAIN's factory function is implemented internally.

Write-direction support for VARIABLE fields (e.g. an output type with an
unbounded 'image' or 'container: vector' field, such as semantic_data or
voice_query) is not yet implemented -- see the TODO markers gen_plugin_cpp
emits inline. FIXED-only output types (e.g. camera_intrinsics) are fully
supported.
"""

from . import types as bg_types
from . import helpers as bg_helpers
from . import codegen_struct as bg_cg_struct
from . import codegen_unity_reader as bg_cg_unity_reader


def gen_wire_header(dotted, td, gen_dotted_names):
    """One unity_wire_<dotted>.hpp per type: struct and flatten function."""
    wire_name = bg_cg_unity_reader.dotted_to_wire_name(dotted)
    fixed, _ = bg_cg_unity_reader.classify_fields(td)
    nested_includes = sorted({
        f'"unity_wire_{field_def["type"].replace(".", "_")}.hpp"'
        for _, field_def in fixed
        if not field_def.get("shape") and (field_def["type"] in gen_dotted_names or field_def["type"] in bg_types.KNOWN_ILLIXR_TYPES)
        })
    lines = [
        f"// Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
        "// SPDX-License-Identifier: BSL-1.0",
        "// This file was generated by the Unity bridge generator -- do not edit directly.",
        "",
        "#pragma once",
        "",
        f'#include "illixr/bridge/{bg_helpers.dotted_to_path(dotted)}.hpp"',
        ]
    for inc in nested_includes:
        lines.append(f"#include {inc}")
    lines += [
        "",
        "#include <algorithm>",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "namespace ILLIXR {",
        "",
        f"struct {wire_name} {{",
        ]
    lines += bg_cg_unity_reader.gen_wire_struct_fields(td, gen_dotted_names)
    lines += [
        "};",
        "",
        f"inline {wire_name} flatten_{dotted.replace('.', '_')}"
        f"(const {bg_helpers.dotted_to_cpp_ns(dotted)}& src) {{",
        f"    {wire_name} out{{}};",
        ]
    lines += bg_cg_unity_reader.gen_flatten_body(td, gen_dotted_names)
    lines += [
        "    return out;",
        "}",
        "",
        "} // namespace ILLIXR",
        "",
        ]
    return "\n".join(lines)


def _bulk_accessor_specs(bridge, type_defs_map, gen_dotted_names_set):
    """Precompute (alias, input_type, td, accessors) for each input once, so
    gen_plugin_hpp and gen_plugin_cpp stay in sync without recomputation
    drift."""
    out = []
    for inp in bridge["inputs"]:
        alias, input_type = inp["alias"], inp["type"]
        td = type_defs_map.get(input_type)
        accessors = bg_cg_unity_reader.gen_bulk_accessors(td, gen_dotted_names_set, type_defs_map,
                                       src=f"(*{alias}_cached_)") if td else []
        out.append((alias, input_type, td, accessors))
    return out


def gen_plugin_hpp(bridge, gen_dotted_names_set, type_defs_map):
    """Generate the plugin header"""
    # pylint: disable=too-many-locals
    plugin_name = bridge["name"]
    all_types = {inp["type"] for inp in bridge["inputs"]} | {out["type"] for out in bridge["outputs"]}
    type_includes = sorted(bg_cg_struct.include_for_type(t, gen_dotted_names_set) for t in all_types)
    wire_includes = sorted(f'"unity_wire_{t.replace(".", "_")}.hpp"' for t in all_types)

    hpp = [
        f"// Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
        "// SPDX-License-Identifier: BSL-1.0",
        "// This file was generated by the Unity bridge generator -- do not edit directly.",
        "",
        "#pragma once",
        "",
        '#include "illixr/phonebook.hpp"',
        '#include "illixr/plugin.hpp"',
        '#include "illixr/switchboard.hpp"',
        ]
    for inc in type_includes:
        hpp.append(f"#include {inc}")
    for inc in wire_includes:
        hpp.append(f"#include {inc}")
    hpp += ["", "namespace ILLIXR {", "", f"class {plugin_name} : public plugin {{", "public:"]
    hpp.append(f"    explicit {plugin_name}(const std::string& name, phonebook* pb);")
    hpp.append(f"    ~{plugin_name}() override = default;")
    hpp.append("")

    for alias, input_type, _, accessors in _bulk_accessor_specs(bridge, type_defs_map, gen_dotted_names_set):
        wire_t = bg_cg_unity_reader.dotted_to_wire_name(input_type)
        hpp.append(f"    bool get_{alias}_info({wire_t}* out_info);")
        for acc in accessors:
            hpp.append(f"    int32_t get_{alias}_{acc['name']}({acc['params']});")
    hpp.append("")

    for out in bridge["outputs"]:
        alias, out_type = out["alias"], out["type"]
        wire_t = bg_cg_unity_reader.dotted_to_wire_name(out_type)
        hpp.append(f"    void send_{alias}(const {wire_t}& info);")
    hpp.append("")

    hpp.append("private:")
    hpp.append("    const std::shared_ptr<switchboard> switchboard_;")
    for inp in bridge["inputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(inp["type"], gen_dotted_names_set)
        hpp.append(f"    switchboard::reader<{cpp_t}> {inp['alias']}_reader_;")
        hpp.append(f"    std::shared_ptr<const {cpp_t}> {inp['alias']}_cached_;")
    for out in bridge["outputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out["type"], gen_dotted_names_set)
        writer_kind = "network_writer" if out["network"] != "none" else "writer"
        hpp.append(f"    switchboard::{writer_kind}<{cpp_t}> {out['alias']}_writer_;")
    hpp += ["};", "", "} // namespace ILLIXR", ""]
    return "\n".join(hpp)


def gen_plugin_cpp(bridge, gen_dotted_names_set, type_defs_map):
    """Generate the plugin cpp file"""
    # pylint: disable=too-many-locals,too-many-statements
    plugin_name = bridge["name"]
    cpp = [
        f"// Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
        "// SPDX-License-Identifier: BSL-1.0",
        "// This file was generated by the Unity bridge generator -- do not edit directly.",
        "",
        f'#include "{plugin_name}.hpp"',
        "",
        "using namespace ILLIXR;",
        "",
        "// Static instance pointer -- exactly one per plugin .so. Set in the",
        "// constructor and used by the extern \"C\" P/Invoke exports below to",
        "// resolve to this instance, independent of how PLUGIN_MAIN's factory",
        "// is implemented internally.",
        f"static {plugin_name}* {plugin_name}_obj = nullptr;",
        "",
        ]

    ctor = [f"{plugin_name}::{plugin_name}(const std::string& name, phonebook* pb)",
            "    : plugin{name, pb}",
            "    , switchboard_{pb->lookup_impl<switchboard>()}"]
    for inp in bridge["inputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(inp["type"], gen_dotted_names_set)
        ctor.append(f"    , {inp['alias']}_reader_{{switchboard_->get_reader<{cpp_t}>(\"{inp['topic']}\")}}")
    for out in bridge["outputs"]:
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out["type"], gen_dotted_names_set)
        writer_kind = "get_network_writer" if out["network"] != "none" else "get_writer"
        extra = ", {}" if out["network"] != "none" else ""
        ctor.append(f"    , {out['alias']}_writer_{{switchboard_->{writer_kind}<{cpp_t}>(\"{out['topic']}\"{extra})}}")
    ctor.append("{")
    ctor.append(f"    {plugin_name}_obj = this;")
    ctor.append("}")
    cpp.append("\n".join(ctor))
    cpp.append("")

    # ---- readers: get_<alias>_info + bulk accessors, each with an extern "C" export ----
    for alias, input_type, td, accessors in _bulk_accessor_specs(bridge, type_defs_map, gen_dotted_names_set):
        wire_t = bg_cg_unity_reader.dotted_to_wire_name(input_type)

        cpp.append(f"bool {plugin_name}::get_{alias}_info({wire_t}* out_info) {{")
        cpp.append(f"    auto val = {alias}_reader_.get_ro_nullable();")
        cpp.append("    if (!val)")
        cpp.append("        return false;")
        cpp.append(f"    {alias}_cached_ = val;")  # keep alive for subsequent bulk accessor calls
        cpp.append(f"    *out_info = flatten_{input_type.replace('.', '_')}(*val);")
        cpp.append("    return true;")
        cpp.append("}")
        cpp.append("")
        cpp.append(f"extern \"C\" int illixr_unity_get_{alias}_info({wire_t}* out_info) {{")
        cpp.append(f"    return ({plugin_name}_obj && {plugin_name}_obj->get_{alias}_info(out_info)) ? 1 : 0;")
        cpp.append("}")
        cpp.append("")

        for acc in accessors:
            cpp.append(f"int32_t {plugin_name}::get_{alias}_{acc['name']}({acc['params']}) {{")
            cpp.append(f"    if (!{alias}_cached_) return 0;")
            cpp += [f"    {l}" for l in acc["body"]]
            cpp.append("}")
            cpp.append("")
            cpp.append(f"extern \"C\" int32_t illixr_unity_get_{alias}_{acc['name']}({acc['params']}) {{")
            param_names = ", ".join(p.strip().split()[-1] for p in acc["params"].split(","))
            cpp.append(f"    return {plugin_name}_obj ? {plugin_name}_obj->get_{alias}_{acc['name']}({param_names}) : 0;")
            cpp.append("}")
            cpp.append("")

    # ---- writers: send_<alias> (FIXED-only fields for now), each with an extern "C" export ----
    for out in bridge["outputs"]:
        alias, out_type = out["alias"], out["type"]
        wire_t = bg_cg_unity_reader.dotted_to_wire_name(out_type)
        td = type_defs_map.get(out_type)
        _, variable = bg_cg_unity_reader.classify_fields(td) if td else ([], [])
        cpp.append(f"void {plugin_name}::send_{alias}(const {wire_t}& info) {{")
        if variable:
            cpp.append(f"    // TODO: '{out_type}' has variable-length fields "
                       f"({', '.join(n for n, _ in variable)});")
            cpp.append("    // write-direction support for these is not yet implemented --")
            cpp.append("    // needs a builder/accumulator across multiple P/Invoke calls.")
        cpp_t = bg_cg_struct.cpp_type_for_switchboard(out_type, gen_dotted_names_set)
        cpp.append(f"    {cpp_t} data;")
        if td:
            fixed, _ = bg_cg_unity_reader. classify_fields(td)
            for field_name, field_def in fixed:
                field_type = field_def["type"]
                shape = field_def.get("shape")
                if shape:
                    n = bg_cg_unity_reader.shape_count(shape)
                    for i in range(n):
                        cpp.append(f"    data.{field_name}_[{i}] = info.{field_name}_{i};" if len(shape) == 1
                                   else f"    // TODO: multi-dim shape flatten for {field_name}")
                elif field_type in gen_dotted_names_set or field_type in bg_types.KNOWN_ILLIXR_TYPES:
                    cpp.append(f"    // TODO: unflatten nested field '{field_name}'")
                else:
                    cpp.append(f"    data.{field_name}_ = info.{field_name}_;")
        cpp.append(f"    auto ev = {alias}_writer_.allocate(std::move(data));")
        cpp.append(f"    {alias}_writer_.put(std::move(ev));")
        cpp.append("}")
        cpp.append("")
        cpp.append(f"extern \"C\" void illixr_unity_send_{alias}(const {wire_t}* info) {{")
        cpp.append(f"    if ({plugin_name}_obj && info)")
        cpp.append(f"        {plugin_name}_obj->send_{alias}(*info);")
        cpp.append("}")
        cpp.append("")

    cpp.append(f"PLUGIN_MAIN({plugin_name})")
    cpp.append("")
    return "\n".join(cpp)


# ---------------------------------------------------------------------------
# CMakeLists.txt -- mirrors codegen_plugin.py's gen_plugin_cmake, minus the
# pybind11/OpenCV-conditional linking Python bridges need. Each Unity bridge
# builds into its own SHARED library, discovered via load_so + PLUGIN_MAIN
# exactly like a Python bridge plugin, so this add_library/install shape is
# intentionally near-identical to gen_plugin_cmake's.
# ---------------------------------------------------------------------------

def gen_plugin_cmake(bridge, gen_dotted_names, gen_serializers, plugin_dir, build_include_dir):
    """Generate the CMakeLists.txt file for the plugin"""
    plugin_name = bridge["name"]
    gen_headers = []
    for dotted in sorted(gen_dotted_names):
        hdr = build_include_dir / "illixr" / "bridge" / (str(bg_helpers.dotted_to_path(dotted)) + ".hpp")
        gen_headers.append(str(hdr))

    all_types = {inp["type"] for inp in bridge["inputs"]} | {out["type"] for out in bridge["outputs"]}
    wire_headers = [str(plugin_dir / f"unity_wire_{t.replace('.', '_')}.hpp") for t in sorted(all_types)]

    cmake = [f"# Copyright 2020-{bg_types.YEAR}, The Board of Trustees of the University of Illinois.",
             "# SPDX-License-Identifier: BSL-1.0",
             "# This file was generated by the Unity bridge generator -- do not edit directly.",
             "",
             "set(PLUGIN_NAME plugin." + plugin_name + "${ILLIXR_BUILD_SUFFIX})",
             "",
             "add_library(${PLUGIN_NAME} SHARED",
             '    "' + str(plugin_dir) + '/plugin.cpp"',
             '    "' + str(plugin_dir) + '/plugin.hpp"']
    for hdr in wire_headers:
        cmake.append('    "' + hdr + '"')
    for hdr in gen_headers:
        cmake.append('    "' + hdr + '"')
    for hdr in gen_serializers:
        cmake.append('    "' + hdr + '"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include/illixr/plugin.hpp"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include/illixr/switchboard.hpp"')
    cmake.append(")")
    cmake.append("")
    cmake.append("target_include_directories(${PLUGIN_NAME} PRIVATE")
    cmake.append('    "' + str(plugin_dir) + '"')
    cmake.append('    "' + str(build_include_dir) + '"')
    cmake.append('    "${CMAKE_SOURCE_DIR}/include"')
    cmake.append(")")
    cmake.append("")
    cmake.append("target_compile_definitions(${PLUGIN_NAME} PRIVATE")
    cmake.append("    PLUGIN_NAME=" + plugin_name)
    cmake.append(")")
    cmake.append("")
    cmake.append("set_target_properties(${PLUGIN_NAME} PROPERTIES")
    cmake.append("    CXX_STANDARD 17")
    cmake.append("    CXX_STANDARD_REQUIRED ON")
    cmake.append(")")
    cmake.append("")
    cmake.append("target_link_libraries(${PLUGIN_NAME} PUBLIC")
    cmake.append("    spdlog::spdlog")
    cmake.append("    Boost::serialization")
    cmake.append(")")
    cmake.append("")
    cmake.append("install(TARGETS ${PLUGIN_NAME} DESTINATION lib)")
    cmake.append("")
    return "\n".join(cmake)
