plugins {
    id 'com.android.application'
}

def root_path = rootProject.getLayout().getProjectDirectory().getAsFile().getPath() + "/third_party/"


android {
    signingConfigs {
        debug {
            storeFile file("${System.getenv('HOME')}/illixr.keystore")
            storePassword 'illixr'
            keyAlias 'illixr'
            keyPassword 'illixr'
        }
        release {
            storeFile file("${System.getenv('HOME')}/illixr.keystore")
            storePassword 'illixr'
            keyAlias 'illixr'
            keyPassword 'illixr'
        }
    }
    compileSdkVersion 33
    ndkVersion '27.2.12479018'

    defaultConfig {
        applicationId = 'com.example.native_activity'
        minSdk 28
        targetSdkVersion 33
        ndk {
            //noinspection ChromeOsAbiSupport
            abiFilters  "arm64-v8a"
        }
        externalNativeBuild {
            cmake {
                version '3.22.1'
                cppFlags '-std=c++17', '-frtti', '-fexceptions'
                arguments "-DTHIRD_PARTY_DIR=${root_path}"
            }
        }
    }

    buildTypes {
        release {
//            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    externalNativeBuild {
        cmake {
            version '3.22.1'
            path '../CMakeLists.txt'

        }
    }
    namespace 'com.example.ILLIXR'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
}
