// Copyright 2020-2026, The Board of Trustees of the University of Illinois.
// SPDX-License-Identifier: BSL-1.0
// This file was generated by generate_python_bridges.py -- do not edit directly.
// Bridge type: illixr.bridge.semantic_xr.query_response

#pragma once

#include "illixr/data_format/point_cloud.hpp"
#include "illixr/data_format/query_response.hpp"

#include <boost/serialization/array.hpp>
#include <boost/serialization/base_object.hpp>
#include <boost/serialization/export.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_free.hpp>

namespace boost {
namespace serialization {

    template<class Archive>
    void serialize(Archive& ar, ILLIXR::data_format::semantic_xr::query_response& data, const unsigned int) {
        ar& boost::serialization::base_object<ILLIXR::switchboard::event>(data);
        ar & data.query_id;
        ar & data.point_clouds;
        ar & data.colors;
        ar & data.num_point_clouds;
        ar & data.server_query_processing;
        ar & data.text_query;
    }

} // namespace serialization
} // namespace boost

BOOST_CLASS_EXPORT_KEY(ILLIXR::data_format::semantic_xr::query_response)
