vcpkg_from_git(
        OUT_SOURCE_PATH SOURCE_PATH
        URL https://github.com/ILLIXR/XNNPACK.git
        REF 1d9c60da32f1d2b5af17470bdab75017cfad9511
)

vcpkg_cmake_configure(
        SOURCE_PATH "${SOURCE_PATH}"
        OPTIONS
            -DCMAKE_BUILD_TYPE=Release
            -DXNNPACK_BUILD_LIBRARY=ON
            -DXNNPACK_BUILD_TESTS=OFF
            -DXNNPACK_BUILD_BENCHMARKS=OFF
            -DXNNPACK_LIBRARY_TYPE=static
            -DXNNPACK_USE_SYSTEM_LIBS=ON
            -DXNNPACK_ENABLE_AVXVNNI=OFF
            -DXNNPACK_ENABLE_ARM_FP16_SCALAR=OFF
            -DXNNPACK_ENABLE_ARM_FP16_VECTOR=OFF
            -DXNNPACK_ENABLE_JIT=OFF
            -DXNNPACK_ENABLE_SPARSE=ON
            -DXNNPACK_ENABLE_GEMM_M_SPECIALIZATION=ON
            -DXNNPACK_ENABLE_ASSEMBLY=ON
            -DXNNPACK_ENABLE_DWCONV_MULTIPASS=ON
            -DXNNPACK_ENABLE_MEMOPT=ON
            -DXNNPACK_ENABLE_AVX512AMX=ON
            -DXNNPACK_ENABLE_ARM_BF16=OFF
            -DXNNPACK_ENABLE_ARM_DOTPROD=OFF
            -DXNNPACK_ENABLE_ARM_I8MM=OFF

)
