plugin_groups:
  - plugin_group:
      - path: offline_imu/
      - path: offline_cam/
      - path: gtsam_integrator/
      - path: pose_prediction/
  - plugin_group:
      - path: ground_truth_slam/
      - path: gldemo/
      - path: debugview/
      - path: offload_data/
  - plugin_group:
      - path: timewarp_gl/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False
# realsense_cam: auto

action:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/ 
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

  ILLIXR_RUN_DURATION: 5 
  ILLIXR_PRE_SLEEP_DURATION: 1

profile: dbg
