plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
      - path: openxrdemo/
      - path: timewarp_gl/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/

enable_offload        : False
enable_alignment      : False
enable_verbose_errors : False
enable_pre_sleep      : False
# realsense_cam: auto

action:
  name: native
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

profile: opt
