#!/usr/bin/env bash
set -Eeuo pipefail

# Runs the ILLIXR unit test suite under gcov instrumentation, then aggregates the results with
# lcov/genhtml into a browsable coverage report: a top-level summary linking into one detailed,
# line-by-line report per unit test component. Requires a build directory configured with both
# -DBUILD_UNIT_TESTS=ON and -DENABLE_UNIT_TEST_COVERAGE=ON (Linux only -- see the
# cmake_dependent_option in CMakeLists.txt).
#
# ILLIXR requires Clang on Linux. Clang's --coverage output self-identifies with an old gcov
# format tag that GNU gcov refuses to read, so lcov needs to be pointed at Clang's own
# llvm-cov gcov instead -- this is detected and required upfront, not treated as an edge case.
#
# Everything this script needs -- which components exist and where their build output lives --
# comes from unit_test_coverage_manifest.txt, generated by CMake at the end of configure. The
# build directory is the only thing this script needs from the caller.

log() { printf '[gather_unit_test_coverage] %s\n' "$*"; }
die() { log "error: $*" >&2; exit 1; }
usage() {
    cat <<'HELP'
Usage: gather_unit_test_coverage.sh --build-dir DIR [options]

  --build-dir DIR   The CMake build directory (configured with -DBUILD_UNIT_TESTS=ON and
                     -DENABLE_UNIT_TEST_COVERAGE=ON). Required.
  --output-dir DIR  Where to write the HTML report. Default: DIR/unit_tests/coverage.
  --open            Open the top-level report in a browser when done (xdg-open).
  -h, --help        Show this help.
HELP
}

BUILD_DIR=""
OUTPUT_DIR=""
OPEN_REPORT=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-dir)
            [[ $# -ge 2 && -n "$2" ]] || die "$1 requires a value."
            BUILD_DIR="$2"; shift 2 ;;
        --output-dir)
            [[ $# -ge 2 && -n "$2" ]] || die "$1 requires a value."
            OUTPUT_DIR="$2"; shift 2 ;;
        --open) OPEN_REPORT=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
done

[[ -n "${BUILD_DIR}" ]] || { usage; die "--build-dir is required."; }
BUILD_DIR="$(realpath -- "${BUILD_DIR}")"
[[ -f "${BUILD_DIR}/CMakeCache.txt" ]] || die "Not a CMake build directory: ${BUILD_DIR}"
: "${OUTPUT_DIR:="${BUILD_DIR}/unit_tests/coverage"}"

command -v lcov >/dev/null || die "lcov is required (e.g. 'sudo apt install lcov')."
command -v genhtml >/dev/null || die "genhtml is required (installed alongside lcov)."

grep -q '^BUILD_UNIT_TESTS:BOOL=ON' "${BUILD_DIR}/CMakeCache.txt" ||
    die "BUILD_UNIT_TESTS is not ON in ${BUILD_DIR}. Reconfigure with -DBUILD_UNIT_TESTS=ON."
grep -q '^ENABLE_UNIT_TEST_COVERAGE:BOOL=ON' "${BUILD_DIR}/CMakeCache.txt" ||
    die "ENABLE_UNIT_TEST_COVERAGE is not ON in ${BUILD_DIR}. Reconfigure with -DENABLE_UNIT_TEST_COVERAGE=ON and rebuild."

# ILLIXR requires Clang on Linux, and Clang-produced coverage data needs llvm-cov, not GNU gcov,
# to read correctly -- confirmed by reproducing lcov's "Incompatible GCC/GCOV version" error
# directly against a Clang-built target. Required upfront, not a fallback.
GCOV_TOOL_ARGS=()
GCOV_WRAPPER=""
cleanup() { [[ -z "${GCOV_WRAPPER}" ]] || rm -f "${GCOV_WRAPPER}"; }
trap cleanup EXIT

CXX_COMPILER="$(grep '^CMAKE_CXX_COMPILER:' "${BUILD_DIR}/CMakeCache.txt" | cut -d= -f2-)"
if [[ -n "${CXX_COMPILER}" ]] && "${CXX_COMPILER}" --version 2>/dev/null | head -1 | grep -qi clang; then
    CLANG_MAJOR="$("${CXX_COMPILER}" --version | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 | cut -d. -f1)"
    LLVM_COV=""
    for CANDIDATE in "llvm-cov-${CLANG_MAJOR}" "llvm-cov"; do
        if command -v "${CANDIDATE}" >/dev/null 2>&1; then
            LLVM_COV="${CANDIDATE}"
            break
        fi
    done
    [[ -n "${LLVM_COV}" ]] ||
        die "Clang was detected (${CXX_COMPILER}) but no matching llvm-cov was found on PATH. Install the llvm-cov package matching this Clang version."
    log "Using '${LLVM_COV} gcov' to read Clang-produced coverage data."
    GCOV_WRAPPER="$(mktemp)"
    printf '#!/usr/bin/env bash\nexec %s gcov "$@"\n' "${LLVM_COV}" > "${GCOV_WRAPPER}"
    chmod +x "${GCOV_WRAPPER}"
    GCOV_TOOL_ARGS=(--gcov-tool "${GCOV_WRAPPER}")
fi

RUNNER="$(find "${BUILD_DIR}/unit_tests" -maxdepth 1 -type f -name 'unit_test_runner*' -perm -u+x | head -n1)"
[[ -n "${RUNNER}" ]] || die "Could not find unit_test_runner in ${BUILD_DIR}/unit_tests -- did the unit_tests target build?"

log "Running ${RUNNER}"
set +e
"${RUNNER}"
RUNNER_STATUS=$?
set -e
if [[ ${RUNNER_STATUS} -ne 0 ]]; then
    log "unit_test_runner exited with status ${RUNNER_STATUS} -- continuing to gather coverage anyway."
fi

MANIFEST="${BUILD_DIR}/unit_tests/unit_test_coverage_manifest.txt"
[[ -f "${MANIFEST}" ]] || die "Coverage manifest not found at ${MANIFEST} -- reconfigure with -DBUILD_UNIT_TESTS=ON -DENABLE_UNIT_TEST_COVERAGE=ON."

mapfile -t MANIFEST_LINES < "${MANIFEST}"
[[ ${#MANIFEST_LINES[@]} -gt 0 ]] || die "Coverage manifest is empty -- no unit test components were registered."

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

SUMMARY_ROWS=()
for LINE in "${MANIFEST_LINES[@]}"; do
    [[ -n "${LINE}" ]] || continue
    IFS='|' read -r TARGET OBJ_DIR <<< "${LINE}"

    if [[ ! -d "${OBJ_DIR}" ]]; then
        log "warning: no object directory for ${TARGET} (${OBJ_DIR}); skipping."
        continue
    fi

    COMPONENT_DIR="${OUTPUT_DIR}/${TARGET}"
    mkdir -p "${COMPONENT_DIR}"
    RAW_INFO="${COMPONENT_DIR}/raw.info"
    FILTERED_INFO="${COMPONENT_DIR}/filtered.info"

    log "Capturing coverage for ${TARGET}"
log "Capturing coverage for ${TARGET}"
    CAPTURE_OUT="$(lcov --quiet --capture --directory "${OBJ_DIR}" --output-file "${RAW_INFO}" \
        "${GCOV_TOOL_ARGS[@]}" \
        --ignore-errors negative,unused,empty,inconsistent,inconsistent 2>&1)" || {
        log "warning: lcov capture failed for ${TARGET}; skipping. Output was:"
        printf '%s\n' "${CAPTURE_OUT}" >&2
        continue
    }

    REMOVE_OUT="$(lcov --quiet --remove "${RAW_INFO}" '/usr/*' '*/_deps/*' '*/tests/*' '*/gtest/*' \
        '*/include/illixr/concurrentqueue/*' \
        '*/include/illixr/imgui/*' \
        '*/include/illixr/gl_util/lib/*' \
        '*/include/illixr/vk/third_party/*' \
        --output-file "${FILTERED_INFO}" \
        --ignore-errors unused,empty,inconsistent,inconsistent 2>&1)" || {
        log "warning: lcov --remove failed for ${TARGET}; using unfiltered coverage data instead. Output was:"
        printf '%s\n' "${REMOVE_OUT}" >&2
        cp "${RAW_INFO}" "${FILTERED_INFO}"
    }

    GENHTML_OUT="$(genhtml --quiet "${FILTERED_INFO}" --output-directory "${COMPONENT_DIR}" \
        --title "${TARGET}" --ignore-errors inconsistent,inconsistent 2>&1)" || {
        log "warning: genhtml failed for ${TARGET}; skipping. Output was:"
        printf '%s\n' "${GENHTML_OUT}" >&2
        continue
    }

    PCT="$(printf '%s\n' "${GENHTML_OUT}" | grep -m1 'lines\.*:' | grep -oE '[0-9]+\.[0-9]+%' | head -n1)"
    PCT="${PCT:-n/a}"
    log "${TARGET}: ${PCT} line coverage"
    SUMMARY_ROWS+=("${TARGET}|${PCT}|${TARGET}/index.html")
done

INDEX="${OUTPUT_DIR}/index.html"
{
    echo '<!DOCTYPE html><html><head><meta charset="utf-8">'
    echo '<title>ILLIXR unit test coverage</title>'
    echo '<style>body{font-family:sans-serif;margin:2em;}table{border-collapse:collapse;}td,th{padding:.4em .8em;border:1px solid #ccc;text-align:left;}</style>'
    echo '</head><body>'
    echo '<h1>ILLIXR unit test coverage</h1>'
    echo "<p>Generated $(date -u '+%Y-%m-%d %H:%M UTC')</p>"
    echo '<table><tr><th>Component</th><th>Line coverage</th><th></th></tr>'
    for ROW in "${SUMMARY_ROWS[@]}"; do
        IFS='|' read -r NAME PCT LINK <<< "${ROW}"
        echo "<tr><td>${NAME}</td><td>${PCT}</td><td><a href=\"${LINK}\">detailed report</a></td></tr>"
    done
    echo '</table></body></html>'
} > "${INDEX}"

log "Report written to ${INDEX}"
if [[ ${OPEN_REPORT} -eq 1 ]]; then
    command -v xdg-open >/dev/null && xdg-open "${INDEX}" || log "xdg-open not found; open ${INDEX} manually."
fi
