cmake_minimum_required(VERSION 3.22)
if(WIN32 OR MSVC OR ANDROID)
    message(WARNING "ada.open3d is supported on Linux CUDA servers")
    set(USE_ADA.OPEN3D OFF)
    return()
endif()

include(GetOpen3D)
get_external(Draco)
find_package(OpenMP REQUIRED COMPONENTS CXX)
set(PLUGIN_NAME plugin.ada.open3d${ILLIXR_BUILD_SUFFIX})
add_library(${PLUGIN_NAME} SHARED plugin.cpp plugin.hpp draco_mesh_builder.hpp reconstruction.cpp reconstruction.hpp)
target_compile_features(${PLUGIN_NAME} PRIVATE cxx_std_17)
target_include_directories(${PLUGIN_NAME} PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(${PLUGIN_NAME} PRIVATE Open3D::Open3D draco_illixr::draco
                      OpenMP::OpenMP_CXX spdlog::spdlog ${OpenCV_LIBRARIES})
if(TARGET draco_static)
    add_dependencies(${PLUGIN_NAME} draco_static)
    target_include_directories(${PLUGIN_NAME} PRIVATE ${draco_illixr_SOURCE_DIR}/src ${CMAKE_BINARY_DIR})
endif()
install(TARGETS ${PLUGIN_NAME} DESTINATION lib)
