set(AUDIO_PIPELINE_CMAKE_ARGS "")
if(HAVE_CENTOS)
    set(AUDIO_PIPELINE_CMAKE_ARGS "-DINTERNAL_OPENCV=${OpenCV_DIR}")
endif()
ExternalProject_Add(Audio_Pipeline
        GIT_REPOSITORY https://github.com/ILLIXR/audio_pipeline.git
        GIT_TAG ca8f56f2e4c77d07aa9afd0fc6c38f21e0fb7416
        PREFIX ${CMAKE_BINARY_DIR}/_deps/audio_pipeline
        DEPENDS ${PortAudio_DEP_STR} ${SpatialAudio_DEP_STR} ${OpenCV_DEP_STR}
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_FLAGS=-L${CMAKE_INSTALL_PREFIX}/lib\ -L${CMAKE_INSTALL_PREFIX}/lib64 -DILLIXR_ROOT=${PROJECT_SOURCE_DIR}/runtime -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX} -DCMAKE_INSTALL_LIBDIR=lib -DILLIXR_BUILD_SUFFIX=${ILLIXR_BUILD_SUFFIX} ${AUDIO_PIPELINE_CMAKE_ARGS}
        )