set(ORB_SLAM_CMAKE_ARGS "")
if(HAVE_CENTOS)
    set(ORB_SLAM_CMAKE_ARGS "-DINTERNAL_OPENCV=${OpenCV_DIR}")
endif()
EXTERNALPROJECT_ADD(ORB_Slam
        GIT_REPOSITORY https://github.com/ILLIXR/ORB_SLAM3.git
        GIT_TAG f79372d50626a84adb0504edd717c5a63231097f
        PREFIX ${CMAKE_BINARY_DIR}/_deps/ORB_Slam
        DEPENDS ${DBoW2_DEP_STR} ${Pangolin_DEP_STR} ${g2o_DEP_STR} ${Sophus_DEP_STR} ${OpenCV_DEP_STR}
        BUILD_COMMAND cmake --build . -j1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_CXX_FLAGS=-L${CMAKE_INSTALL_PREFIX}/lib -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DILLIXR_ROOT=${PROJECT_SOURCE_DIR}/runtime ${ORB_SLAM_CMAKE_ARGS}
        )