delimiter: ','

root_path: /home/tirthankar/Downloads/rgbd_dataset_freiburg1_360

image:
  # timestamp units aren't mentioned, so the default of nanoseconds
  # will be used.
  - rgb:
      # TUM only has one RGB image stream
      - path: rgb
  - depth:
      # ... and one depth image stream
      - path: depth

ground_truth:
  path: groundtruth.txt
  format: 3, 4
  name: position, orientation
