delimiter: ' '

root_path: /home/tirthankar/Downloads/vcu_lab_simple1

image:
  # timestamp units aren't mentioned, so the default of nanoseconds
  # will be used.
  rgb:
    path:
      # VCU only has one RGB image stream
      - color
  depth:
    path:
      # ... and one depth image stream
      - depth

ground_truth:
  path: lab_simple1_gt.csv
  format: 3, 4
  name: position, orientation