name: Docker Build and Test

runs-on: [self-hosted]

on:
  push:
    branches: [ main, misc/ci ]
  pull_request:
    branches: [ main, misc/ci ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Give xhost access on host machine
      run: |
        xhost +local:root

    - name: Build Docker image
      run: |
        docker build -t illixr-ci-${GITHUB_SHA::8} -f docker/ci/Dockerfile .

    - name: Run Docker container
      id: docker_run
      continue-on-error: true
      run: |
        docker run --rm -e DISPLAY=$DISPLAY -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all -v $GITHUB_WORKSPACE:/opt/ILLIXR -v /tmp/.X11-unix:/tmp/.X11-unix --runtime=nvidia illixr-ci-${GITHUB_SHA::8}
        echo "status=$?" >> $GITHUB_OUTPUT

    - name: Set commit status
      uses: actions/github-script@v7
      with:
        script: |
          const status = context.steps.docker_run.outputs.status === '0' ? 'success' : 'failure';
          const description = status === 'success' 
            ? 'Docker tests passed successfully'
            : `Docker tests failed with exit code ${context.steps.docker_run.outputs.status}`;
          
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.name,
            sha: context.sha,
            state: status,
            description: description,
            context: 'Docker CI'
          });
