name: Docker Build and Test

on:
  push:
    branches: [ main, misc/ci ]
  pull_request:
    branches: [ main, misc/ci ]

jobs:
  illixr-ci:
    runs-on: [self-hosted]

    env:
      DISPLAY: :1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Give xhost access on host machine
      run: |
        xhost +local:root

    - name: Build Docker image
      id: docker_build
      continue-on-error: true
      run: |
        cd docker/ci
        docker build -t illixr-ci-${GITHUB_SHA::8} -f Dockerfile .
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"

    - name: Run Docker container
      id: docker_run
      if: steps.docker_build.outputs.exit_code == '0'
      continue-on-error: true
      run: |
        docker run --rm -e DISPLAY=$DISPLAY -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all -v $GITHUB_WORKSPACE:/opt/ILLIXR -v /tmp/.X11-unix:/tmp/.X11-unix --runtime=nvidia illixr-ci-${GITHUB_SHA::8}
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"

    - name: Set commit status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          let status = 'failure';
          let description = '';
          
          const buildExitCode = '${{ steps.docker_build.outputs.exit_code }}';
          const runExitCode = '${{ steps.docker_run.outputs.exit_code }}';
          
          if (buildExitCode !== '0') {
            description = `Docker build failed with exit code ${buildExitCode}`;
          } else if (runExitCode === '') {
            description = 'Docker run step was skipped';
          } else if (runExitCode === '0') {
            status = 'success';
            description = 'Docker tests passed successfully';
          } else {
            description = `Docker tests failed with exit code ${runExitCode}`;
          }
          
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.name,
            sha: context.sha,
            state: status,
            description: description,
            context: 'Docker CI'
          });
